# Site settings
title: kodnin
email: kodnin@gmail.com
description: “Exploring Ruby, Clojure and JavaScript”
baseurl: ""
url: "http://kodnin.github.io"
twitter_username: kodnin
github_username: kodnin

# Build settings
markdown: kramdown

# Custom settings
full_title: kodnin (David Boot)
friendly_url: "kodnin.github.io"
heroku_url: "http://kodnin.com"
friendly_heroku_url: "kodnin.com"
